apiVersion: v1
kind: Service
metadata:
  name: simple_jwt_api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: simple_jwt_api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple_jwt_api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: simple_jwt_api
  template:
    metadata:
      labels:
        app: simple_jwt_api
    spec:
      containers:
        - name: simple_jwt_api
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 5000