apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  name: simple-jwt-api-2
=======
  name: simple-jwt-api
>>>>>>> df1f33f6ac8e21dffcfed2c263644c6998f3ab3e
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
<<<<<<< HEAD
    app: simple-jwt-api-2
=======
    app: simple-jwt-api
>>>>>>> df1f33f6ac8e21dffcfed2c263644c6998f3ab3e
---
apiVersion: apps/v1
kind: Deployment
metadata:
<<<<<<< HEAD
  name: simple-jwt-api-2
=======
  name: simple-jwt-api
>>>>>>> df1f33f6ac8e21dffcfed2c263644c6998f3ab3e
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
<<<<<<< HEAD
      app: simple-jwt-api-2
  template:
    metadata:
      labels:
        app: simple-jwt-api-2
    spec:
      containers:
        - name: simple-jwt-api-2
=======
      app: simple-jwt-api
  template:
    metadata:
      labels:
        app: simple-jwt-api
    spec:
      containers:
        - name: simple-jwt-api
>>>>>>> df1f33f6ac8e21dffcfed2c263644c6998f3ab3e
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          env:
<<<<<<< HEAD
          - name: JWT_SECRET
            value: JWT_SECRET_VALUE
          ports:
            - containerPort: 5000
=======
            - name: JWT_SECRET
              value: JWT_SECRET_VALUE
          ports:
            - containerPort: 5000
>>>>>>> df1f33f6ac8e21dffcfed2c263644c6998f3ab3e
