apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::342476802371:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1XYCDXUNVBR5U
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::342476802371:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-08T04:20:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5242"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 94a1c550-aede-458b-9866-94a2ab8332d4