apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::342476802371:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1P426IWFL7Q8D
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-27T05:59:33Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-01-27T05:59:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1261"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: fa8ebd7b-1b05-4b52-b5bb-3652753b6c40
